server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JiaYicard/springcloud-config.git     #填写你自己的github路径
          search-paths:
            - springcloud-config      #仓库名称
      label: main     #分支名称

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
