server:
  port: 80


eureka:
  client:
    register-with-eureka: true   #表识不向注册中心注册自己
    service-url:
      defaultZone:  http://localhost:7001/eureka,http://eureka7002.com:7002/eureka   #设置与eureka server交互的地址查询

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.zzs.springcloud.service.PaymentFeignService:  debug